esphome:
  name: esp32irgw
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "YOUR_WIFI_NET_NAME"
  password: "YOUR_WIFI_PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails.
  ap:
    ssid: "Esp32Rcgw Hotspot"
    password: "d-diot.com"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
# Wifi signal monitor
  - platform: wifi_signal
    name: "ESP32-IR-GW WiFi Signal"
    update_interval: 60s

# Receiver configuration
remote_receiver:
  pin:
    number: GPIO32
    mode: INPUT_PULLUP
    inverted: true
  dump:
    - lg
    - nec
    - panasonic
    - pioneer
    - jvc
    - samsung
    - sony
    - raw

# Transmitter configuration
remote_transmitter:
  pin: GPIO33
  carrier_duty_percent: 50%


########################### EXAMPLE SAMSUNG REMOTE BN59-01175P - ARROW UP BUTTON  ###########################################


switch:
# Receiver Led switch
  - platform: gpio
    pin: GPIO27
    id: 'ir_input_led'
    internal: true
# Block transmission switch
  - platform: template
    name: "Block transmission switch"
    id: 'block_sw'
    internal: true
    optimistic: true
# Samsung BN59-01175P - Arrow Up button    
  - platform: template
    name: "Button: Samsung BN59-01175P - Arrow Up"
    id: "samsung_arrow_up"
    icon: "mdi:arrow-up"
    # Turn ON code
    turn_on_action:
      then: 
        - delay: 500ms
        - if: 
            condition: 
              switch.is_off: block_sw
            then:        
              - logger.log: "Evaluated Block switch as OFF, transmitting IR code"
              - remote_transmitter.transmit_samsung:
                  data: 0xE0E006F9
                  repeat: 
                    times: 1
                    wait_time: 0ms
        - if: 
            condition: 
              switch.is_on: block_sw
            then:        
              - logger.log: "Evaluated Block switch as ON, flipping it"
              - switch.turn_off: block_sw
  
# Example Arrow UP button press detection (binary sensor)
binary_sensor:
  - platform: remote_receiver
    name: "Receiver: Samsung BN59-01175P - Arrow Up"
    internal: true
    samsung: 
      data: 0xE0E006F9
    on_press:
      then:
        - switch.turn_on: block_sw 
        - switch.turn_on: ir_input_led
        - delay: 100ms
        - switch.turn_off: ir_input_led 
        - switch.turn_on: samsung_arrow_up